project:
  type: website
  output-dir: docs

website:
  title: "Stephanie J. Lao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Papers
      - href: portfolio.qmd
        text: Portfolio
      - href: skills.qmd
        text: Skills
  google-analytics: "G-WLVLPRJF12"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual