---
title: "Selected Papers"
---

## Statistical Calibration of a Compartmental Epidemic Model with Applications to the West Texas Measles Outbreak

[View it on eScholarship](https://escholarship.org/uc/item/23q5x727)

[View it on ProQuest](https://www.proquest.com/dissertations-theses/statistical-calibration-compartmental-epidemic/docview/3230617235/se-2)

Master's Thesis at University of California, Los Angeles

Advisor: Xiaowu Dai

Mathematical models used in epidemiology, such as compartmental models, have the power to reveal the risk of infectious disease outbreaks and can impact the course of action for public health interventions. Despite these models being inexact at capturing the complexities of real-world disease transmission, they are capable of providing meaningful insight into physical systems and can ultimately support decision-making. These models use input parameters that represent characteristics of the physical system of interest. However, the true values of these parameters are often unknown because they cannot be directly measured. Hence, statistical calibration, or the process of identifying the optimal values of these parameters to best fit the observed data, is utilized to improve predictions and reliability of the model.

Although declared an eradicated disease in the United States in 2000, there has been recent attention on several measles outbreaks throughout the country, most notably an outbreak beginning in Gaines County, Texas at the start of 2025. Here, we employ a dynamic compartmental model, known as an SVEIR model, to study the transmission of measles. We perform four different statistical calibration methods on the SVEIR model using daily incidence data from the West Texas outbreak collected by the Texas Department of State Health Services. We report estimated parameter values and basic reproduction numbers for the model calibrated using different methods. We give a comparison of predictive root mean square errors of all calibration methods and find that the optimal prediction calibration method returned the lowest predictive error. This study highlights the differences in calibration methods, hopes to provide an improved understanding of the current state of the ongoing measles outbreak in West Texas, and underscores avenues for future analysis.

## Interpretable Predictive Modeling of Factors Influencing Deep Sea Coral Growth in Davidson Seamount

Undergraduate Capstone at St. Edward's University

Advisor: Paul Savala

Although the largest ecosystem on Earth, the deep ocean is also the least explored and understood. Hence, we are still in need of properly integrated biodiversity studies to unlock the patterns controlling species diversity in cold-water coral habitats. This study is specific to Davidson Seamount, a volcano located about 80 kilometers off the central California coast in the Monterey Bay National Marine Sanctuary. Predictive modeling has only recently been developed and applied in the marine environment due to the remoteness and limited accessibility of this environment. The objectives of this study are to develop and validate interpretable models to predict the occurrence of deep sea species of coral and sponges in Davidson Seamount.

For this study we utilize a subset tailored to Davidson Seamount of coral records from the Deep-Sea Coral Research and Technology Program of the National Oceanic and Atmospheric Administration (NOAA). The dataset contains information about deep sea corals and sponges collected by NOAA and their partners and is specifically tailored to the occurrences of azooxanthellates. Additionally, we utilized hydrographic records obtained from California Cooperative Oceanic Fisheries Investigations (CalCOFI). CalCOFI hydrographic data consists of the physical seawater properties measured over a 69 year time-series. The dataset contains seawater measurements from bottle sample depths. Our precise implementation takes the form of a glass-box explainable boosting machine, which are a special form of gradient boosted decision trees. Our results show that the most important factors influencing coral growth given the data include depth, temperature, salinity, dynamic height, and potential density. Our model reveals the most favorable conditions involving these factors for the occurrence of different coral in Davidson Seamount.
